apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapi
  namespace: b2kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendapi
  template:
    metadata:
      labels:
        app: frontendapi
    spec:
      containers:
      - name: frontendapi
        image: xtestacr113.azurecr.io/frontendapi:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env: 
         - name: CONNECTIONSTRINGS__BACKENDTASKAPI
           value: "http://backendapi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontendapi
  namespace: b2kapp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontendapi
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: b2kapp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  #- host: k8stestcluster.westeurope.cloudapp.azure.com
  - host: frontend.7abbb0589a004c68b42a.westeurope.aksapp.io
    http:
      paths:
        # - path: /frontend(/|$)(.*)
        - path: /
          pathType: Prefix
          backend:
           service: 
            name: frontendapi
            port: 
              name: http