apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageapi
  namespace: b2kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageapi
  template:
    metadata:
      labels:
        app: storageapi
    spec:
      containers:
      - name: storageapi
        image: xtestacr113.azurecr.io/storageapi:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: storageapi
  namespace: b2kapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: storageapi
