apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
  namespace: b2kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
      - name: backendapi
        image: xtestacr113.azurecr.io/backendapi:latest
        ports:
        - containerPort: 80
        env: 
         - name: CONNECTIONSTRINGS__STORAGETASKAPI
           value: "http://storageapi.b2kapp.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: backendapi
  namespace: b2kapp
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: backendapi