apiVersion: apps/v1
kind: Deployment
metadata:
  #name: aks-helloworld  
  name: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: k8stestacr113.azurecr.io/taskmanagementapi:latest
        ports:
        - containerPort: 80
        #env:
        # - name: ConnectionStrings__TaskApi
        #   value: "backend.93b7f3cb06d9488dbdbc.westeurope.aksapp.io"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: backend-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-service-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: backend.93b7f3cb06d9488dbdbc.westeurope.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: backend-service
            port: 
              number: 80