# # Description
# ##############
# # Buid and deploy WebAPI as container image to ACR
# ##############
# # Triggered manually 
# ##############

# name: Build & Deploy Web Api
# on: 

#   workflow_dispatch:
#     inputs: 
#       service_name:
#         description: 'Service to deploy'
#         required: true
#         type: choice
#         options:
#         # monikers to the respective apps - when new app is added this list should be changed
#         - backend-api
#         - storage-api
#         - frontend-api

#  # reference of the actual app by its moniker 
# env: 
#   backend-app: './src/Services/BackendApi.csproj'
#   storage-app: './src/Services/StorageApi.csproj'
#   frontend-app: './src/Services/FrontendApi.csproj'
  
# jobs:
#   init:
#   # dump all information about the service and wofkflow
#     name: Init workflow
#     runs-on: ubuntu-latest
#     outputs:
#       service_path: ${{steps.setup}}
#     steps:
#       - id: setup
#       - name: Get path to the app
#         run: echo "::set-output name=service_path::${{env[github.event.inputs.service_name]}}"
    
#   get_sources:
#     runs-on: ubuntu-latest
#     needs: init
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v3
#         with:
#          fetch-dept: 0

#       - name: Replace NuGet Token
#         run: | 
#           Get-Content ./${{needs.init.outputs.service_path}}
#         shell: pwsh  
        
          
        
        
  
  