# Description
##############
# Buid and deploy WebAPI as container image to ACR
##############
# Triggered manually 
##############

name: Build & Deploy Web Api
on: 

  workflow_dispatch:
    inputs: 
      service_name:
        description: 'Service to deploy'
        required: true
        type: choice
        options:
        - app01
        - app02 
  
env: 
  app01: './src/WebApp01/WebApp01.proj'
  app02: './src/WebApp02/WebApp02.proj'
  NUGET_ACCESS_TOKEN: 'iddqd 12345 idkfa'
  
jobs:
  init_workflow:
    name: Init WF
    runs-on: ubuntu-latest   
    outputs:
      service_path: ${{steps.setup}}
    steps:
      - name: Setup
        run: |
          echo "SERVICE_PATH=${{env[github.event.inputs.service_name]}}" >> $GITHUB_ENV
          echo "::set-output name=service_path::$SERVICE_PATH"
      

  build_n_deploy:
    needs: init_workflow
    name: Build and deploy
    uses: vitaly-pavluk/bstest-net/.github/workflows/build_app.yaml@main
    with: 
      service_path: ${{needs.init_workflow.outputs.service_path}}
    secrets: 
      NUGET_ACCESS_TOKEN: ${{secrets.NUGET_TOKEN}}
        
          
        
        
  
  