name: MATRIX TEST BUILD 
on: 
 pull_request:
   branches:
    - main  # branch that PR targets 
   paths:
   # restrict changes to only specific path to avoid deploying any other service
    - 'src/Services/Services.BackendApi/**' 


jobs:
 init:
  runs-on: ubuntu-latest
  outputs:
   the_matrix: 
     ${{ steps.build_matrix.outputs.the_files }}
  steps:
   - name: build MATRIX
     id: build_matrix
     run: |
       echo "::set-output name=the_files::['file_01', 'file_02', 'file_03']"
     shell: pwsh

 build_files:
   runs-on: ubuntu-latest
   needs: [init]
   strategy:
      matrix:
        value: ${{fromJson(needs.init.outputs.the_matrix)}}
   steps:
    - name: build files
      run: | 
        echo "Run step against: ${{ matrix.value }}"
      shell: pwsh
      

